[package]
name = "vm-memory"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"

[dependencies]
vm-memory-upstream = { package = "vm-memory", git = "https://github.com/rust-vmm/vm-memory", branch = "master", features = ["backend-mmap", "backend-bitmap"] }
libc = ">=0.2.80"

[dev-dependencies]
utils = { path = "../utils" }
